// Generated by Selenium IDE

package edu.pitt.cs;
import static org.hamcrest.MatcherAssert.assertThat;
import org.junit.FixMethodOrder;
import org.junit.runners.MethodSorters;
import java.time.Duration;
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import org.openqa.selenium.chrome.ChromeOptions;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;



@FixMethodOrder(MethodSorters.NAME_ASCENDING)
public class D3Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() 
  {
    ChromeOptions options = new ChromeOptions();
    options.addArguments("--headless");
    driver = new ChromeDriver(options);
    driver.manage().timeouts().implicitlyWait(Duration.ofSeconds(30));
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void tEST1LINKS() {
    driver.get("http://localhost:8080/");
    driver.manage().window().setSize(new Dimension(1552, 832));
    {
      WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(3));
      wait.until(ExpectedConditions.presenceOfElementLocated(By.linkText("Reset")));
    }
    driver.findElement(By.linkText("Reset")).click();
    {
      WebElement element = driver.findElement(By.linkText("Reset"));
      String attribute = element.getAttribute("href");
      vars.put("storedHref", attribute);
    }
    assertEquals(vars.get("storedHref").toString(), "/reset");
  }
  @Test
  public void tEST2RESET() {
    driver.get("http://localhost:8080");
    js.executeScript("document.cookie = \"1=true\";document.cookie = \"2=true\";document.cookie = \"3=true\";");
    driver.findElement(By.linkText("Reset")).click();
    assertThat(driver.findElement(By.xpath("//*[@id=\"listing\"]/ul/li[1]")).getText(), is("ID 1. Jennyanydots"));
    assertThat(driver.findElement(By.xpath("//*[@id=\"listing\"]/ul/li[2]")).getText(), is("ID 2. Old Deuteronomy"));
    assertThat(driver.findElement(By.xpath("//*[@id=\"listing\"]/ul/li[3]")).getText(), is("ID 3. Mistoffelees"));
  }
  @Test
  public void tEST3CATALOG() {
    driver.get("http://localhost:8080");
    driver.findElement(By.linkText("Catalog")).click();
    {
      WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(3));
      wait.until(ExpectedConditions.presenceOfElementLocated(By.xpath(" //html/body/div/main/div[1]/ol/li[2]/img")));
    }
    {
      WebElement element = driver.findElement(By.xpath("//html/body/div/main/div[1]/ol/li[2]/img"));
      String attribute = element.getAttribute("src");
      vars.put("imageSrc", attribute);
    }
    assertEquals(vars.get("imageSrc").toString(), "http://localhost:8080/images/cat2.jpg");
  }
  @Test
  public void tEST4LISTING() {
    driver.get("http://localhost:8080");
    driver.findElement(By.linkText("Catalog")).click();
    {
      WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(3));
      wait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("//*[@id=\"listing\"]/ul")));
    }
    vars.put("catCount", driver.findElements(By.xpath("//*[@id=\"listing\"]/ul/li")).size());
    assertEquals(vars.get("catCount").toString(), "3");
  }
  @Test
  public void tEST5RENTACAT() {
    driver.get("http://localhost:8080");
    driver.findElement(By.linkText("Rent-A-Cat")).click();
    assertThat(driver.findElement(By.xpath("//html/body/div/main/div[1]/div[2]/div[3]/button")).getText(), is("Rent"));
    assertThat(driver.findElement(By.xpath("//html/body/div/main/div[1]/div[3]/div[3]/button")).getText(), is("Return"));
  }
  @Test
  public void tEST6RENT() {
    driver.get("http://localhost:8080");
    driver.findElement(By.linkText("Reset")).click();
    driver.findElement(By.linkText("Rent-A-Cat")).click();
    {
      WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(3));
      wait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("//*[@id=\"rentID\"]")));
    }
    driver.findElement(By.xpath("//*[@id=\"rentID\"]")).sendKeys("1");
    driver.findElement(By.xpath("//html/body/div/main/div[1]/div[2]/div[3]/button")).click();
    assertThat(driver.findElement(By.xpath("//*[@id=\"listing\"]/ul/li[1]")).getText(), is("Rented out"));
    assertThat(driver.findElement(By.xpath("//*[@id=\"listing\"]/ul/li[2]")).getText(), is("ID 2. Old Deuteronomy"));
    assertThat(driver.findElement(By.xpath("//*[@id=\"listing\"]/ul/li[3]")).getText(), is("ID 3. Mistoffelees"));
    assertThat(driver.findElement(By.xpath("//*[@id=\"rentResult\"]")).getText(), is("Success!"));
  }
  @Test
  public void tEST7RETURN() {
    driver.get("http://localhost:8080");
    driver.findElement(By.linkText("Reset")).click();
    js.executeScript("document.cookie = \"1=false\";document.cookie = \"2=true\";document.cookie = \"3=false\";");
    driver.findElement(By.linkText("Rent-A-Cat")).click();
    {
      WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(3));
      wait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("//*[@id=\"returnID\"]")));
    }
    driver.findElement(By.xpath("//*[@id=\"returnID\"]")).sendKeys("2");
    driver.findElement(By.xpath("//html/body/div/main/div[1]/div[3]/div[3]/button")).click();
    assertThat(driver.findElement(By.xpath("//*[@id=\"listing\"]/ul/li[1]")).getText(), is("ID 1. Jennyanydots"));
    assertThat(driver.findElement(By.xpath("//*[@id=\"listing\"]/ul/li[2]")).getText(), is("ID 2. Old Deuteronomy"));
    assertThat(driver.findElement(By.xpath("//*[@id=\"listing\"]/ul/li[3]")).getText(), is("ID 3. Mistoffelees"));
    assertThat(driver.findElement(By.xpath("//*[@id=\"returnResult\"]")).getText(), is("Success!"));
  }
  @Test
  public void tEST8FEEDACAT() {
    driver.get("http://localhost:8080");
    driver.findElement(By.xpath("//html/body/div/header/nav/ul/li[4]/a")).click();
    assertThat(driver.findElement(By.xpath("//html/body/div/main/div[1]/div[2]/div[3]/button")).getText(), is("Feed"));
  }
  @Test
  public void tEST9FEED() {
    driver.get("http://localhost:8080");
    driver.findElement(By.xpath("//html/body/div/header/nav/ul/li[4]/a")).click();
    {
      WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(3));
      wait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("//*[@id=\"catnips\"]")));
    }
    driver.findElement(By.xpath("//*[@id=\"catnips\"]")).sendKeys("6");
    driver.findElement(By.xpath("//html/body/div/main/div[1]/div[2]/div[3]/button")).click();
    assertThat(driver.findElement(By.xpath("//*[@id=\"feedResult\"]")).getText(), is("Nom, nom, nom."));
  }
  @Test
  public void tEST10GREETACAT() {
    driver.get("http://localhost:8080");
    driver.findElement(By.xpath("//html/body/div/header/nav/ul/li[6]/a")).click();
    assertThat(driver.findElement(By.xpath("//*[@id=\"greeting\"]/h4")).getText(), is("Meow!Meow!Meow!"));
  }
  @Test
  public void tEST11GREETACATWITHNAME() {
    driver.get("http://localhost:8080/greet-a-cat/Jennyanydots");
    assertThat(driver.findElement(By.xpath("//*[@id=\"greeting\"]/h4")).getText(), is("Meow! from Jennyanydots."));
  }
}
